### ISSUE TITLE
Invalid file paths cause the installer to say that the xdk setup file  is invalid 

### ISSUE THREAD

**Issue by Flamelord626** [Team-Resurgent/RXDK#1]
To replicate this issue all you to is have a file path that has a folder with spaces in it but the weirder part is that is you use a invalid folder path then a valid one then use the invalid one it works fine until you reboot the installer so that's also interesting

**Comment by astarivi** [comment]
Successfully reproduced on v1.3, Windows 11, XDK path:

`D:\a a a a a\XDKSetup5849.17.exe`

Result:

![image](https://github.com/user-attachments/assets/3dceedc0-0ada-4565-b475-cb3dac42b4a1)
